// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeZIZOh7atLnJq5uNdhzwxmkMqsUW56Ag',
    appId: '1:27397708355:web:cec5cad9366dc795ed12f6',
    messagingSenderId: '27397708355',
    projectId: 'cpm-iasop',
    authDomain: 'cpm-iasop.firebaseapp.com',
    databaseURL: 'https://cpm-iasop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cpm-iasop.appspot.com',
    measurementId: 'G-9ZPR2VZMFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08Qy9KXUo5_MvxUEq1CvkVJDMT8l2rIE',
    appId: '1:27397708355:android:c1d0d5deb48da511ed12f6',
    messagingSenderId: '27397708355',
    projectId: 'cpm-iasop',
    databaseURL: 'https://cpm-iasop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cpm-iasop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKTH63WKEhZyR-wizY0dyhAdXYOBFTYPU',
    appId: '1:27397708355:ios:c16ecac76a178be6ed12f6',
    messagingSenderId: '27397708355',
    projectId: 'cpm-iasop',
    databaseURL: 'https://cpm-iasop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cpm-iasop.appspot.com',
    iosBundleId: 'com.example.iasop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKTH63WKEhZyR-wizY0dyhAdXYOBFTYPU',
    appId: '1:27397708355:ios:c16ecac76a178be6ed12f6',
    messagingSenderId: '27397708355',
    projectId: 'cpm-iasop',
    databaseURL: 'https://cpm-iasop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cpm-iasop.appspot.com',
    iosBundleId: 'com.example.iasop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeZIZOh7atLnJq5uNdhzwxmkMqsUW56Ag',
    appId: '1:27397708355:web:67d02c8e4faaf8e8ed12f6',
    messagingSenderId: '27397708355',
    projectId: 'cpm-iasop',
    authDomain: 'cpm-iasop.firebaseapp.com',
    databaseURL: 'https://cpm-iasop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cpm-iasop.appspot.com',
    measurementId: 'G-XXSYCKVBRC',
  );
}
